import type { Trade, Service, TradeSettings, TradeObjectMapping } from "@/lib/supabase/types";

const now = () => new Date().toISOString();

const baseSettings = (mobilizationCost: number, minimumJobCharge: number, defaultMargin = 0.25): TradeSettings => ({
  mobilizationCost,
  minimumJobCharge,
  defaultMargin,
});

export const services: Service[] = [
  {
    id: "svc-asph-overlay",
    organization_id: null,
    trade_id: "trade-asphalt",
    name: "HMA Overlay 2\"",
    code: "ASPH-OVL",
    description: "Hot mix asphalt overlay",
    unit: "sq ft",
    production_rate: null,
    crew_size: 4,
    labor_rate: 0.85,
    material_cost: 1.45,
    equipment_cost_fixed: 0,
    equipment_cost_hourly: 0.35,
    waste_factor: 1.05,
    minimum_charge: 5000,
    minimum_quantity: 0,
    is_default: true,
    is_active: true,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-seal-2coat",
    organization_id: null,
    trade_id: "trade-seal",
    name: "Coal Tar 2-Coat",
    code: "SEAL-2C",
    description: "Sealcoat application, two coats",
    unit: "sq ft",
    production_rate: null,
    crew_size: 2,
    labor_rate: 0.04,
    material_cost: 0.08,
    equipment_cost_fixed: 0,
    equipment_cost_hourly: 0.02,
    waste_factor: 1,
    minimum_charge: 1500,
    minimum_quantity: 0,
    is_default: true,
    is_active: true,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-striping-stall",
    organization_id: null,
    trade_id: "trade-striping",
    name: "Standard Stall",
    code: "STRP-STALL",
    description: "Parking stall striping",
    unit: "each",
    production_rate: null,
    crew_size: 2,
    labor_rate: 3.5,
    material_cost: 1.25,
    equipment_cost_fixed: 0,
    equipment_cost_hourly: 0.5,
    waste_factor: 1,
    minimum_charge: 800,
    minimum_quantity: 0,
    is_default: true,
    is_active: true,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-striping-ada",
    organization_id: null,
    trade_id: "trade-striping",
    name: "ADA Stall Complete",
    code: "STRP-ADA",
    description: "ADA stall marking",
    unit: "each",
    production_rate: null,
    crew_size: 2,
    labor_rate: 45,
    material_cost: 35,
    equipment_cost_fixed: 0,
    equipment_cost_hourly: 5,
    waste_factor: 1,
    minimum_charge: 350,
    minimum_quantity: 0,
    is_default: true,
    is_active: true,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-striping-fire",
    organization_id: null,
    trade_id: "trade-striping",
    name: "Fire Lane Curb",
    code: "STRP-FIRE",
    description: "Fire lane curb striping",
    unit: "lin ft",
    production_rate: null,
    crew_size: 2,
    labor_rate: 0.75,
    material_cost: 0.45,
    equipment_cost_fixed: 0,
    equipment_cost_hourly: 0.15,
    waste_factor: 1,
    minimum_charge: 350,
    minimum_quantity: 0,
    is_default: true,
    is_active: true,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-striping-crosswalk",
    organization_id: null,
    trade_id: "trade-striping",
    name: "Crosswalk",
    code: "STRP-XWALK",
    description: "Crosswalk striping",
    unit: "sq ft",
    production_rate: null,
    crew_size: 2,
    labor_rate: 0.85,
    material_cost: 0.65,
    equipment_cost_fixed: 0,
    equipment_cost_hourly: 0.2,
    waste_factor: 1,
    minimum_charge: 350,
    minimum_quantity: 0,
    is_default: true,
    is_active: true,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-striping-arrow",
    organization_id: null,
    trade_id: "trade-striping",
    name: "Directional Arrow",
    code: "STRP-ARROW",
    description: "Directional arrow marking",
    unit: "each",
    production_rate: null,
    crew_size: 2,
    labor_rate: 18,
    material_cost: 8,
    equipment_cost_fixed: 0,
    equipment_cost_hourly: 2,
    waste_factor: 1,
    minimum_charge: 350,
    minimum_quantity: 0,
    is_default: true,
    is_active: true,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-striping-edge",
    organization_id: null,
    trade_id: "trade-striping",
    name: "4\" Edge Line",
    code: "STRP-EDGE",
    description: "Edge line striping",
    unit: "lin ft",
    production_rate: null,
    crew_size: 2,
    labor_rate: 0.15,
    material_cost: 0.08,
    equipment_cost_fixed: 0,
    equipment_cost_hourly: 0.03,
    waste_factor: 1,
    minimum_charge: 350,
    minimum_quantity: 0,
    is_default: true,
    is_active: true,
    created_at: now(),
    updated_at: now(),
  },
];

const asphaltConsumes: TradeObjectMapping[] = [
  {
    objectType: "parking-surface",
    quantitySource: "area",
    serviceId: "svc-asph-overlay",
    wasteFactor: 1.05,
  },
  {
    objectType: "drive-lane",
    quantitySource: "area",
    serviceId: "svc-asph-overlay",
    wasteFactor: 1.05,
  },
  {
    objectType: "loading-area",
    quantitySource: "area",
    serviceId: "svc-asph-overlay",
    wasteFactor: 1.05,
  },
];

const sealConsumes: TradeObjectMapping[] = [
  {
    objectType: "parking-surface",
    quantitySource: "area",
    serviceId: "svc-seal-2coat",
  },
  {
    objectType: "drive-lane",
    quantitySource: "area",
    serviceId: "svc-seal-2coat",
  },
];

const stripingConsumes: TradeObjectMapping[] = [
  {
    objectType: "parking-stall",
    quantitySource: "count",
    serviceId: "svc-striping-stall",
  },
  {
    objectType: "stall-group",
    quantitySource: "count",
    serviceId: "svc-striping-stall",
  },
  {
    objectType: "ada-space",
    quantitySource: "count",
    serviceId: "svc-striping-ada",
  },
  {
    objectType: "fire-lane",
    quantitySource: "length",
    serviceId: "svc-striping-fire",
  },
  {
    objectType: "crosswalk",
    quantitySource: "area",
    serviceId: "svc-striping-crosswalk",
  },
  {
    objectType: "directional-arrow",
    quantitySource: "count",
    serviceId: "svc-striping-arrow",
  },
  {
    objectType: "edge-line",
    quantitySource: "length",
    serviceId: "svc-striping-edge",
  },
];

export const trades: Trade[] = [
  {
    id: "trade-asphalt",
    organization_id: null,
    name: "Asphalt Paving",
    code: "ASPH",
    description: "Asphalt paving and patching",
    color: "#374151",
    consumes: asphaltConsumes,
    settings: baseSettings(1500, 5000),
    is_default: true,
    is_active: true,
    sort_order: 1,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "trade-seal",
    organization_id: null,
    name: "Sealcoating",
    code: "SEAL",
    description: "Sealcoating and surface protection",
    color: "#1f2937",
    consumes: sealConsumes,
    settings: baseSettings(500, 1500),
    is_default: true,
    is_active: true,
    sort_order: 2,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "trade-striping",
    organization_id: null,
    name: "Striping & Markings",
    code: "STRP",
    description: "Parking lot striping",
    color: "#fbbf24",
    consumes: stripingConsumes,
    settings: baseSettings(350, 800),
    is_default: true,
    is_active: true,
    sort_order: 3,
    created_at: now(),
    updated_at: now(),
  },
];
